# Generated by Django 2.1.1 on 2018-09-30 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 9, 30, 20, 29, 34, 838952)),
        ),
    ]
