# Generated by Django 2.1.1 on 2018-09-24 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_from',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
